yoheimuta/protolint

- .goreleaser.yml
- Makefile
- README.md
- _example/config/.protolint.yaml
- cmd/protolint/main.go
- internal/cmd/cmd.go
ref. [pl is ambiguous with ASCII propertery list utility in osx · Issue #20 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/20)
> Renamed pl to protolint

- README.md
- internal/addon/rules/serviceNamesEndWithRule.go
- internal/addon/rules/serviceNamesEndWithRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/rulesOption.go
- internal/linter/config/serviceNamesEndWithOption.go
This is a rule that checks whether or not the services defined in the .proto file all end with the given text. The Uber tool does this with API, and Google seems to recommend Service.
We prefer to use Service, but this gives the end user the ability to specify whatever text they want.
> Implement SERVICE_NAMES_END_WITH rule

- README.md
- _testdata/rules/indentrule/enum.proto
- _testdata/rules/indentrule/incorrect_enum.proto
- _testdata/rules/indentrule/incorrect_message.proto
- _testdata/rules/indentrule/message.proto
- internal/addon/rules/indentRule.go
- internal/addon/rules/indentRule_test.go
- internal/addon/rules/maxLineLengthRule.go
- internal/addon/rules/maxLineLengthRule_test.go
Changed the default values so that corresponding with the updated Style Guide.
- https://developers.google.com/protocol-buffers/docs/style#standard-file-formatting
> Correspond line length and indent size

- go.mod
- go.sum
ref. [Block followed by semicolon causing runtime error · Issue #66 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/66)
> chore: Bump parser to v3.1.0

- README.md
ref. [Support custom lint rule · Issue #65 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/65)
> chore: Add a simple note about plugin

- _testdata/rules/indentrule/issue_74.proto
- go.mod
- go.sum
- internal/addon/rules/indentRule_test.go
ref. [False-positive by indent rule · Issue #74 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/74)
> fix: Handle the case that the last rpc method of a service is having a statement block

- _example/proto/issue_88/oneof_options.proto
- go.mod
- go.sum
ref. [oneof options fail to parse · Issue #88 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/88)
> feat: Update parser to allow oneof to have options

- go.mod
- linter/disablerule/command.go
This should fix \#116.
Uses strings.Fields() instead of strings.Split(x, " "), to avoid empty strings in rules.
Unsure whether the strings.TrimSpace() call is necessary when using Fields, but I'll take the sanity check.
> Make sure to strip whitespace on regex calls, to ensure rules are in the expected format.

- go.mod
ref. 
- https://github.com/yoheimuta/protolint/pull/118
- https://app.circleci.com/jobs/github/yoheimuta/protolint/502
[memo] I guess this misleading behavior should be fixed somehow (or PR CI should fail fast).
> fix: Include dependencies that are automatically injected.

- .circleci/config.yml
- Dockerfile.protolint
- go.mod
ref. [fix: Include dependencies that are automatically injected. by yoheimuta · Pull Request #119 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/pull/119)
For fixing the annoying go.mod diff below.
```
⨯ release failed after 13.22s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
M go.mod
```
- ref. https://circleci.com/gh/yoheimuta/protolint/502
> chore: Update go version to latest

- internal/cmd/cmd.go
- internal/cmd/protocgenprotolint/cmd.go
- internal/cmd/subcmds/lint/cmdLint.go
- internal/cmd/subcmds/list/cmdList.go
- internal/osutil/exitCode.go
This changes the current exit code behaviour to be dependent on the error type returned.
exitcode 1: internal error
exitcode 2: runtime error
exitcode 3: linting error
exitcode 4: parsing error
This is an iniial implementation of the error handling changes suggested in \#101.
However, having recognised that not all error codes are necessarily linting or parsing, but can also be runtime (eg mem violation) or internal (eg usage: missing args, unknown flags, etc), I have expanded the error codes available.
> Change exit code behaviour to return debuggable values

- go.mod
- go.sum
ref. [Release Allow the comment without a newline · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/releases/tag/v4.1.0)
> chore: Update the parser

- _testdata/parser/issue_123.proto
- go.mod
- go.sum
```
❯❯❯ make build/cmd/protolint
go build \
-ldflags "-X github.com/yoheimuta/protolint/internal/cmd.version=`git describe --tags --abbrev=0` -X github.com/yoheimuta/protolint/internal/cmd.revision=`git rev-parse --short HEAD`" \
-o protolint \
cmd/protolint/main.go
❯❯❯ ./protolint _testdata/parser
found "\"}\"(Token=15, Pos=_testdata/parser/issue_123.proto:6:22)" but expected [ident] at /Users/yoshimutayohei/.go/pkg/mod/github.com/yoheimuta/go-protoparser/v4@v4.1.0/parser/option.go:93. Use -v for more details
❯❯❯ make build/cmd/protolint
go build \
-ldflags "-X github.com/yoheimuta/protolint/internal/cmd.version=`git describe --tags --abbrev=0` -X github.com/yoheimuta/protolint/internal/cmd.revision=`git rev-parse --short HEAD`" \
-o protolint \
cmd/protolint/main.go
go: downloading …
```
> Fix empty fields within option/123

- README.md
- internal/cmd/cmd.go
- internal/cmd/subcmds/lint/flags.go
> add -no-error-on-unmatched-pattern option to lint

- internal/linter/file/protoSet.go
ref. [Unexpected error when you run a protolint from the working directory which is symlink · Issue #136 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/136)
> fix: Calculate the correct relative target path even when the cwd is symlink

- _example/config/.protolint.yaml
- internal/filepathutil/platform.go
- internal/linter/config/directories.go
- internal/linter/config/externalConfig_test.go
- internal/linter/config/files.go
- internal/linter/config/ignore.go
- internal/stringsutil/slice.go
ref. [protolint.yaml: File paths are not uniformly handled in UNIX and Windows · Issue #143 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/143)
> Support the cross-platform file path format in a config file

- .pre-commit-hooks.yaml
- README.md
This adds the yaml configuration for a [pre-commit](https://pre-commit.com) hook for `protolint`.  When you have `pre-commit` installed and this is added to your local pre-commit yaml configuration file, it will run `protolint` via the official docker image on all staged changes to `.proto` files.
> pre-commit hook configuration

- .pre-commit-hooks.yaml
- README.md
Add a new pre-commit hook to install protolint with go.
Change the existing pre-commit hook id to include docker.
This will allow pre-commit to use either Go or Docker to run protolint, depending on which hook id is selected in the `.pre-commit-config.yaml` config.
Updated after comment from pre-commit maintainer at https://github.com/pre-commit/pre-commit.com/pull/455
> Allow pre-commit to install protolint with go

- .pre-commit-hooks.yaml
Language should be `golang` instead of `go`. Sorry for the confusion.
https://pre-commit.com/#golang
> Fix pre-commit hook

- _example/proto/issue_140/negative_enum_field.proto
- go.mod
- go.sum
ref. [Linter fails on negative enum values · Issue #140 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/140)
> Fixed: Linter fails on negative enum values

- internal/cmd/cmd.go
- internal/cmd/subcmds/lint/cmdLint.go
- internal/linter/config/externalConfig.go
- internal/linter/config/externalConfigProvider.go
- internal/linter/config/externalConfigProvider_test.go
ref. [Protolint linting Proto files in node_modules · Issue #155 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/155)
> Handle config file path more explicitly

- README.md
- internal/addon/rules/packageNameLowerCaseRule.go
- internal/addon/rules/packageNameLowerCaseRule_test.go
- linter/strs/strs.go
ref. [Feature: accept "_" in package names (PACKAGE_NAME_LOWER_CASE) · Issue #153 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/153)
> Allow a snake_case package name

- README.md
- _example/config/.protolint.yaml
- _example/proto/simple.proto
- internal/addon/rules/rpcNamesCaseRule.go
- internal/addon/rules/rpcNamesCaseRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/rpcNamesCaseOption.go
- internal/linter/config/rpcNamesCaseOption_test.go
- internal/linter/config/rulesOption.go
- linter/strs/strs.go
- linter/strs/strs_test.go
ref. [Configurable naming conventions · Issue #160 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/160)
I added a new rule, `RPC_NAME_CASE,` in this PR, instead of modifying the existing rule `RPC_NAMES_UPPER_CAMEL_CASE` to accept a new option like `convention.`  
That's because, in the latter, the rule name can contradict the actual behavior controlled by the specified convention. 
Also, I didn't rename `RPC_NAMES_UPPER_CAMEL_CASE` to `RPC_NAMES_CASE` with its default to upper_camel_case.
I feel like it's more beneficial for most users to keep the nearly official best practice to be the first class in this tool.
Besides, I'm not sure it's worth changing with extra effort in a backward compatibility manner.
As a result of these considerations, these two rules result …
> Add a new rule named RPC_NAME_CASE

- .github/dependabot.yml
This is adding a configuration file to enable dependabot for version updates to gomod and Dockerfile.  The configuration is currently set to check daily for gomod and weekly for Dockerfile but that is easy to change if desired.
> feat: Add dependabot configuration

- README.md
- internal/cmd/protocgenprotolint/cmd.go
ref. 
- https://github.com/yoheimuta/protolint/pull/184#issuecomment-958604152
- https://medium.com/golangspec/detect-locks-passed-by-value-in-go-efb4ac9a3f2b
> fix: pass an reference of the struct with lock

- _example/config/.protolint.yaml
- internal/addon/rules/importsSortedRule.go
- internal/addon/rules/importsSortedRule_test.go
- internal/addon/rules/indentRule.go
- internal/addon/rules/indentRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/importsSortedOption.go
- internal/linter/config/indentOption.go
- linter/fixer/fixer.go
This refactoring allows users to go without specifying newline in yaml config.
It results in the newline field of importsSortedRule and indentRule deprecated.
> Refactor fixers

- .github/workflows/codeql-analysis.yml
I have added the default codeql github workflow file.  The only changes were to fix yamllint linting errors.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
> feat: add codeql analysis

- internal/cmd/protocgenprotolint/cmd.go
ref. https://github.com/yoheimuta/protolint/issues/234
I checked the support locally as below.
```
(base) ❯ cat test.proto
syntax = "proto3";
package test;
message Test {
optional string foo = 1;
}
(base) ❯ protoc --protolint_out=. test.proto
```
```
(base) ❯ cat test3.proto
syntax = "proto3";
package test;
message testTest {
optional string foo = 1;
}
(base) ❯ protoc --protolint_out=. test3.proto
[test3.proto:5:1] Message name "testTest" must be UpperCamelCase like "TestTest"
--protolint_out: protoc-gen-protolint: Plugin failed with status code 1.
```
> feat: Signal proto3 optional support

- internal/cmd/subcmds/lint/cmdLint.go
- internal/cmd/subcmds/pluginFlag.go
ref. https://github.com/yoheimuta/protolint/issues/237
I confirmed it locally that no process was lingering after the parent exit.
```
(base) ❯ ./protolint -plugin ./plugin_example ./_example/proto/
(base) ❯ ps aux | grep plugin
yoheimuta        36711   0.0  0.0  4399420    772 s047  S+    6:46PM   0:00.00 grep --color plugin
```
> fix: Clean up plugin clients by registering them to managedClients

- .goreleaser.yml
ref. https://github.com/yoheimuta/protolint/issues/251
Confirmed locally.
```
(base) ❯ goreleaser release --snapshot --skip-publish --rm-dist
• releasing...
• loading config file       file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...               commit=b0681c8edea6caf8392ac7e954a76a3043dc19d0 latest tag=v0.38.2
• pipe skipped              error=disabled during snapshot mode
• parsing tag
• running before hooks
• running                   hook=go mod download
• setting defaults
• snapshotting
• github/gitlab/gitea releases
• project name
• loading go mod information
• building binaries
• creating source archive
• archives
• linux packages
• snapcraft packages
• calculating checksums
• signing artifacts
• signing docker images
• docker …
```
> dev: Build and publish multi arch docker images

- .github/workflows/goreleaser.yml
ref. 
- https://github.com/yoheimuta/protolint/runs/7053095562?check_suite_focus=true
- https://github.com/yoheimuta/protolint/issues/251
```
#7 [2/3] RUN apk -U --no-cache upgrade; /bin/rm -rf /var/cache/apk/*
#0 0.215 standard_init_linux.go:228: exec user process caused: exec format error
#7 ERROR: executor failed running [/bin/sh -c apk -U --no-cache upgrade; /bin/rm -rf /var/cache/apk/*]: exit code: 1
------
> [2/3] RUN apk -U --no-cache upgrade; /bin/rm -rf /var/cache/apk/*:
#0 0.215 standard_init_linux.go:228: exec user process caused: exec format error
------
error: failed to solve: executor failed running [/bin/sh -c apk -U --no-cache upgrade; /bin/rm -rf /var/cache/apk/*]: exit code: 1
```
> Set up QEMU to fix exec format error

- _proto/plugin.proto
- internal/cmd/subcmds/list/cmdList.go
- internal/cmd/subcmds/list/flags.go
ref. https://github.com/yoheimuta/protolint/pull/261
```
(base) ❯ ./protolint list -plugin ./plugin_example
...
ENUM_NAMES_LOWER_SNAKE_CASE: Verifies that all enum names are LowerSnakeCase.
SIMPLE: Simple custom rule.
```
> Fix some minors of https://github.com/yoheimuta/protolint/pull/261

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yml
The container-scan action is running trivy and dockle.  This repository is already running the hadolint action and dockle doesn't have a github action, so I think it's ok to skip dockle and just run trivy instead.
You might need to enable Code Scanning on the project Code Security and Analysis settings if you haven't already done that. https://github.com/yoheimuta/protolint/settings/security_analysis should be the link to get there I hope.
I used the config example from https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning and we have already enabled the CodeQL scanning in .github/workflow.
This article https://medium.com/pvs-studio/how-to-get-nice-error-reports-using-sarif-in-github-68df5d4ff335 seems to give a good overview on viewing SARIF results in …
> Change from container-scan to trivy

- .github/workflows/go.yml
- .github/workflows/shellcheck.yml
- .github/workflows/yamllint.yml
`codeql-action/upload-sarif` action doesn't run on regular push trigger.
Removing the push trigger will also remove the duplicate workflow runs when a pull request is opened.
> fix: run workflows only on pull_request

- _example/proto/issue_292/trailingcomment3.proto
- go.mod
- go.sum
- internal/addon/rules/rpcsHaveCommentRule.go
- internal/addon/rules/rpcsHaveCommentRule_test.go
ref. https://github.com/yoheimuta/protolint/issues/292#issuecomment-1305356269
```
(base) ❯ ./protolint -config_path ./_example/proto/issue_292/.notgostyle.yaml ./_example/proto/issue_292
[_example/proto/issue_292/trailingcomment.proto:3:1] Message "xyz" should have a comment
```
```
(base) ❯ protolint -config_path ./_example/proto/issue_292/.notgostyle.yaml ./_example/proto/issue_292
[_example/proto/issue_292/trailingcomment.proto:3:1] Message "xyz" should have a comment
[_example/proto/issue_292/trailingcomment3.proto:4:3] RPC "GetAll" should have a comment
```
> Consider rpc trailing comment/292

- README.md
ref.
- https://github.com/Homebrew/homebrew-core/pull/117858
- https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fprotolint
```
(base) ❯ brew info protolint
==> protolint: stable 0.42.2 (bottled), HEAD
Pluggable linter and fixer to enforce Protocol Buffer style and conventions
https://github.com/yoheimuta/protolint
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/protolint.rb
License: MIT
==> Dependencies
Build: go ✘
==> Options
--HEAD
Install HEAD version
==> Analytics
install: 34 (30 days), 34 (90 days), 34 (365 days)
install-on-request: 34 (30 days), 34 (90 days), 34 (365 days)
build-error: 1 (30 days)
```
> Add a note about homebrew-core

- README.md
From the previous style guide page:
This site is deprecated. The site will be turned down after January 31, 2023, and traffic will redirect to the new site at https://protobuf.dev. In the meantime, updates will be made only to protobuf.dev.
> Update Style Guide link

- .github/workflows/goreleaser.yml
- .gitignore
- CONTRIBUTING.md
- README.md
- _example/gradle/.gitignore
- _example/gradle/README.md
- _example/gradle/build.gradle
- _example/gradle/settings.gradle
- _example/gradle/src/main/proto/demo.proto
- build.gradle
- cmd/protoc-gen-protolint/README.md
- settings.gradle
This PR aims to give a method of publishing protoc-gen-protolint to maven central.
This aims to address issue https://github.com/yoheimuta/protolint/issues/328.
A maven central account is required, and this will have to be added to the repositories secrets, under these variables:
- OSSRH_USERNAME
- OSSRH_TOKEN
This guide can be used to apply for an account: https://central.sonatype.org/publish/publish-guide/#introduction
I have previously done this for testing, and here is an example of the issue I opened: https://issues.sonatype.org/browse/OSSRH-50791
Also signing is done by GPG and requires 2 new secrets to be provided:
- GPG_SIGNING_KEY: The GPG key in armoured form.
- GPG_SIGNING_PASSWORD: The password for signing the artifact.
If a GPG key does not already exist, this guide can be …
> Issue #328 Add deployment to Maven Central

- _example/gradle/build.gradle
The example provided for gradle used a placeholder version as there wasn't a first release. Now that we have a first release published to maven, we can use the released version and see the example working. So upgrade to the first released version.
> Issue #328 Include released version in examples

- internal/linter/config/directories.go
Previously, a config of the form:
```
lint:
directories:
exclude:
- vendor/
```
would not ignore files in the `vendor` directory, since we would be attempting to match paths that begin with `vendor//`.
To fix this, we only append the path separator when the target does not already end in one.
> fix: allow ignored directories that already end in a path separator

- README.md
- internal/cmd/subcmds/lint/cmdLint.go
- internal/cmd/subcmds/lint/cmdLintConfig.go
- internal/cmd/subcmds/lint/flags.go
- internal/cmd/subcmds/lint/reporterFlag.go
- internal/linter/report/reporter.go
- internal/linter/report/reporters/ciReporter.go
- internal/linter/report/reporters/ciReporter_test.go
- internal/linter/report/reporters/sonarReporter.go
- internal/linter/report/reporters/sonarReporter_test.go
> feat: Improve CI/CD usage

- _testdata/rules/enumFieldNamesUpperSnakeCase/disable_next.proto
- _testdata/rules/enumFieldNamesUpperSnakeCase/disable_this.proto
- _testdata/rules/enumFieldNamesUpperSnakeCase/invalid.proto
- _testdata/rules/enumFieldNamesUpperSnakeCase/upperSnakeCase.proto
- internal/addon/rules/enumFieldNamesPrefixRule_test.go
- linter/strs/strs.go
- linter/strs/strs_test.go
ref. https://github.com/yoheimuta/protolint/issues/341
> fix: Make ToSnakecase correct in the way converting from camel-case strings starting with a 2-letter abbreviation

- linter/disablerule/interpreter.go
- linter/disablerule/interpreter_test.go
ref. https://github.com/yoheimuta/protolint/issues/345
> fix: protolint:disable MAX_LINE_LENGTH works with a disable comment that has a different ruleID

- .github/workflows/publish_npm.yml
in #356 it was mentioned, that the upload did not
work.
First issue seems to be, that the package.json cannot be found. The root cause seems to be, that the
working directory is not correct.
This should work
> fix: NPM packages cannot be published

- .github/workflows/publish_npm.yml
After re-reading the documentation, #356 should be fixed
> ci: Save credentials to local npmrc

- .github/workflows/publish_npm.yml
According to latest documentation (https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration) we need a scoped AUTH Token to support multiple registries. Even the default token must be prefixed.
Should fix #356
> ci: Use scoped AUTH_TOKEN

- README.md
- bdist/py/setup.py
Package `protolint` was already taken. Using `protolint-bin` as new python wheel name.
> fix!: New python wheel name

- .github/workflows/publish_wheel.yml
- bdist/py/ReadMe.rst
- bdist/py/setup.py
Wheels have been rejected by pypi.
Setting up an own ReadMe with rst file and
using an encoding will help.
The workflow has now been equipped with a linter
as quality gate
> fix: Linter issue on markdown rendering

- _example/proto/issue_368/disabled_rpc_names_upper_camel_case.proto
- _example/proto/issue_368/invalid_rpc_names_upper_camel_case.proto
- _testdata/rules/rpcNamesUpperCamelCase/disable_this_left_curly.proto
- go.mod
- go.sum
- internal/addon/rules/rpcNamesUpperCamelCaseRule_test.go
- linter/visitor/extendedDisableRuleVisitor.go
fix: https://github.com/yoheimuta/protolint/issues/368
See also https://github.com/yoheimuta/go-protoparser/pull/85
> fix: RPC_NAMES_UPPER_CAMEL_CASE disable is ignored when RPC has either leftcurly comment or embedded comments

- bdist/py/setup.py
This time it has been tested with https://test.pypi.org (after I created an account) The upload is now working.
> fix: Package Upload to wheel

- _testdata/validconfig/protolint.yaml
- internal/linter/config/customizableSeverityOption.go
- internal/linter/config/enumFieldNamesZeroValueEndWithOption.go
- internal/linter/config/enumFieldsHaveCommentOption.go
- internal/linter/config/enumsHaveCommentOption.go
- internal/linter/config/externalConfigProvider_test.go
- internal/linter/config/fieldNamesExcludePrepositionsOption.go
- internal/linter/config/fieldsHaveCommentOption.go
- internal/linter/config/fileNamesLowerSnakeCaseOption.go
- internal/linter/config/importsSortedOption.go
- internal/linter/config/indentOption.go
- internal/linter/config/maxLineLengthOption.go
- internal/linter/config/messageNamesExcludePrepositionsOption.go
- internal/linter/config/messagesHaveCommentOption.go
- internal/linter/config/quoteConsistentOption.go
- internal/linter/config/repeatedFieldNamesPluralizedOption.go
- internal/linter/config/rpcNamesCaseOption.go
- internal/linter/config/rpcsHaveCommentOption.go
- internal/linter/config/serviceNamesEndWithOption.go
- internal/linter/config/servicesHaveCommentOption.go
- internal/linter/config/syntaxConsistentOption.go
I tried to fix https://github.com/yoheimuta/protolint/issues/416
I am no go expert (yet), so review is definitely required.
I also extended the existing unit test.
> Fixed severity config via protolint yaml config

- bdist/js/ReadMe.md
- bdist/js/install.mjs
The proxy variable will be used correctly. The HTTPS_PROXY / HTTP_PROXY will be used, if PROTOLINT_PROXY is not set.
Evaluation takes place: if the remote url starts with https, HTTPS_PROXY will be used, otherwise HTTP_PROXY will be used.
This interpretation is questionable, but makes sense in the first place.
Closes #426
> fix: Proxy Agent usage

- bdist/js/install.mjs
- bdist/js/package-lock.json
- bdist/js/package.json
Configure 'Got' to use `HttpsProxyAgent` for `https` URLs 
(e.g. when default protolint host is used as in `https://github.com/yoheimuta/protolint/releases/download/....`)
Related to #427
@carstencodes  I would really appreciate it if you could take a look at it.
> Configure 'Got' to use HttpsProxyAgent for https URLs

- go.mod
- go.sum
Inlcude parser fix from go-protoparser, allowing to correctly parse protobuf files being migrated to opaque API (see https://protobuf.dev/reference/go/opaque-migration/)
https://github.com/yoheimuta/go-protoparser/releases/tag/v4.13.0
> feat: Update go-protoparser to support braced identifiers in option names

- README.md
- internal/cmd/cmd.go
Introduce support for the `--version` and `-v` flags to display the protolint version. Update documentation to reflect these changes.
> Add version flag support to protolint command

- README.md
- release.sh
Introduce a `release.sh` script to automate the creation and pushing of release tags, reducing human error in the release process. Update the README to include usage instructions for the new script.
> Add release automation script to streamline the release process

- README.md
- cmd/pl/main.go
- cmd/protolint/main.go
- internal/cmd/cmd.go
- internal/cmd/lint_runner.go
- internal/cmd/subcmds/lint/reporterFlag.go
- internal/linter/report/reporters/mcpReporter.go
- internal/linter/report/reporters/mcpReporter_test.go
- lib/lint.go
- lib/lint_test_runner.go
- mcp/README.md
- mcp/protocol.go
- mcp/protocol_test.go
- mcp/server.go
- mcp/server_test.go
- mcp/tools.go
- mcp/tools_test.go
This pull request introduces significant enhancements to `protolint`, including the addition of Model Context Protocol (MCP) server functionality, a new MCP reporter, and related documentation updates. These changes enable `protolint` to integrate with AI tools like Claude Desktop and provide structured linting results in MCP-friendly formats.
* Added support for the Model Context Protocol (MCP), allowing `protolint` to act as an MCP server for AI model integration (`internal/cmd/cmd.go`, `mcp/README.md`, `README.md`). [[1]](diffhunk://#diff-c7a088a8c769fd043c752c9f91d78566891415e294c5c020c77e2cab0da2b8e8R21) [[2]](diffhunk://#diff-bbc432cf1e07824fdbc95e27cadce87efa4198c88f4f42de801c90836e710517R1-R145) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 …
> Implement Model Context Protocol (MCP) server for protolint

- bdist/js/bin/protoc-gen-protolint.js
- bdist/js/bin/protolint.js
> refactor: replace execFile with spawn for better process handling

- README.md
- internal/cmd/lint_runner.go
- internal/libinternal/lint.go
- lib/lint.go
- lib/lint_test.go
- lib/mock_lint_runner_test.go
- mcp/tools.go
This pull request refactors the `protolint` codebase to improve modularity by introducing a new `libinternal` package and updating the usage of linting functionality across the project. It also includes changes to streamline testing and enhance error handling. Below is a summary of the most important changes:
* Introduced a new `libinternal` package to encapsulate core linting logic, including the `Lint` function, `LintRunner` interface, and error definitions (`ErrLintFailure` and `ErrInternalFailure`). This improves separation of concerns and reduces coupling between internal components (`internal/libinternal/lint.go`).
* Updated the `lib` package to delegate linting logic to `libinternal`, simplifying its implementation. The `lib.Lint` function now auto-initializes the default runner if …
> Fix library usage

- _testdata/rules/fileNamesLowerSnakeCase/dot.separated.proto
- internal/addon/rules/fileNamesLowerSnakeCaseRule.go
- internal/addon/rules/fileNamesLowerSnakeCaseRule_test.go
- internal/addon/rules/importsSortedRule.go
- internal/addon/rules/indentRule.go
- internal/addon/rules/orderRule.go
- linter/visitor/baseFixableVisitor.go
- linter/visitor/baseVisitor.go
- linter/visitor/extendedAutoDisableVisitor.go
- linter/visitor/extendedDisableRuleVisitor.go
- linter/visitor/hasExtendedVisitor.go
This pull request introduces several changes to enhance the functionality of proto file linting, primarily by refactoring the `Finally` methods across various visitors to accept a `*parser.Proto` parameter. Additionally, it improves handling of file name rules and introduces new test cases to validate these updates.
* Updated the `Finally` method in `BaseVisitor`, `BaseFixableVisitor`, and other visitor implementations (`indentVisitor`, `orderVisitor`, etc.) to accept a `*parser.Proto` parameter for better context during finalization. [[1]](diffhunk://#diff-28d606329e28c8e507cfb0f3bc42c8a26427ad7c5a3f7b1585f383d1f8fb1c7eL10-R11) [[2]](diffhunk://#diff-6e2dde8ae2b692cf264af1badca44eb929f582b58ecc00b875373f709eec47cfL35-R40) [[3]](diffhunk://#diff-2d997f749705f98166c302d787bc7c3e40ca10e1d622 …
> Fix disabling FILE_NAMES_LOWER_SNAKE_CASE

- go.mod
In a recent change (8ffaae4, chore: update Go version to 1.24.2), we upgraded the minimum Go version in `go.mod` from Go 1.23 to Go 1.24.2. The intention was seemingly to have the CI jobs to run with a newer Go version. Since we updated the minimum version in `go.mod`, the module is no longer usable from modules that support earlier Go versions as well.
Drop the required Go version to back to 1.23. It doesn't seem like we use any 1.24 features that would require us to bump the minimum version.
> Set minimum Go version to 1.23

- internal/cmd/protocgenprotolint/cmd.go
- internal/osutil/file.go
- internal/util_test/testFile.go
- linter/fixer/fixer.go
This PR replaces function usages from `io/ioutil` with the same functions from `io` and `os`.
- replace `ioutil.ReadFile` with `os.ReadFile`
- replace `ioutil.ReadAll` with `io.ReadAll`
[io/ioutil](https://pkg.go.dev/io/ioutil) is deprecated:
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
> refactor: replace deprecated io/ioutil with io and os

- README.md
- _example/config/.protolint.yaml
- internal/addon/rules/fieldNumbersOrderAscendingRule.go
- internal/addon/rules/fieldNumbersOrderAscendingRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/rulesOption.go
This rule checks the cases like: 
```
message Example1{
string field1 = 1;
string field2 = 1;
}
message Example2{
string field1 = 2;
string field2 = 1;
}
message Example3{
string field1 = one;
}
```
for messages and enums
> add new rule FIELD_NUMBERS_ORDER_ASCENDING
