yoheimuta/protolint

- go.mod
- go.sum
ref. [vague errors e.g. found { but expected [constant] · Issue #21 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/21#issuecomment-501198802)
> chore: Bump go-protoparser

- go.mod
- go.sum
- internal/addon/rules/internal/visitor/baseVisitor.go
- internal/addon/rules/internal/visitor/extendedDisableRuleVisitor.go
ref. [found "extend" but expected [;] · Issue #27 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/27)
> chore: Bump go-protoparser and fix trivial incompat issues

- README.md
ref. [Notice: vscode-protobuflint · Issue #25 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/25)
> chore: Add users list

- .goreleaser.yml
ref. [Suggestion: Windows Release · Issue #30 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/30)
> chore: Generated windows binaries

- README.md
- _example/config/.protolint.yaml
- _example/proto/simple.proto
- internal/addon/rules/fieldNamesExcludePrepositionsRule.go
- internal/addon/rules/fieldNamesExcludePrepositionsRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/fieldNamesExcludePrepositionsOption.go
- internal/linter/config/rulesOption.go
- internal/strs/strs.go
- internal/strs/strs_test.go
ref. https://cloud.google.com/apis/design/naming_convention#field_names
> feat: Add FIELD_NAMES_EXCLUDE_PREPOSITIONS

- _example/config/.protolint.yaml
- internal/cmd/subcmds/lint/cmdLint.go
- internal/linter/config/externalConfig.go
- internal/linter/config/files.go
Change-Id: I0aeb51048c665ca53f65b4325f70a16cfaaf40b6
1. Support exclude files
2. We shouldn't parse proto file if there is nothing to check
> Support exclude files and skip files that has no rules

- internal/addon/rules/enumFieldNamesUpperSnakeCaseRule.go
- internal/addon/rules/enumFieldNamesUpperSnakeCaseRule_test.go
- internal/addon/rules/fieldNamesLowerSnakeCaseRule.go
- internal/addon/rules/fieldNamesLowerSnakeCaseRule_test.go
Change-Id: I26b9fe9ff6e26534063f15b25a32582f75f8901a
> update failure msg for easy understanding

- _testdata/rules/indentrule/issue_63.proto
- internal/addon/rules/indentRule.go
- internal/addon/rules/indentRule_test.go
ref. [INDENT rule doesn't handle "extend" properly · Issue #63 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/63)
> FIX: INDENT rule doesn't handle "extend" properly

- _example/proto/simple.proto
- go.mod
- go.sum
ref. [Block followed by semicolon causing runtime error · Issue #66 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/66)
> Fix block semicolon

- _example/plugin/README.md
ref. [Seg fault with example plugin · Issue #76 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/76)
> chore: Add a README to _example/plugin

- go.mod
- internal/cmd/cmd.go
- internal/cmd/subcmds/lint/flags.go
- internal/cmd/subcmds/pluginFlag.go
ref. [DEBUG log entries from plugin contained in JUnitReporter output · Issue #81 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/81)
> feat: Suppress plugin debug logs by default

- go.mod
- go.sum
ref. [Allow multiline string literal constants by pleask · Pull Request #38 · yoheimuta/go-protoparser](https://github.com/yoheimuta/go-protoparser/pull/38)
> chore: Update go-protoparser

- .goreleaser.yml
- Makefile
- README.md
- internal/cmd/cmd.go
ref. [Command line argument for version info · Issue #67 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/67)
> feat: Add a version command

- .dockerignore
- Dockerfile.protolint
ref. [is there a plan to publish docker images? · Issue #92 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/92)
> dev: Add Dockerfile.protolint

- README.md
ref. [is there a plan to publish docker images? · Issue #92 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/92)
> dev: Add notes about Docker

- README.md
- internal/cmd/protocgenprotolint/cmd.go
- internal/cmd/subcmds/lint/cmdLint.go
- internal/cmd/subcmds/lint/flags.go
ref. [Support -output flag · Issue #83 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/83)
> feat: Add -output_file

- _testdata/rules/indentrule/incorrect_issue_99.proto
- _testdata/rules/indentrule/issue_99.proto
- internal/addon/rules/indentRule.go
- internal/addon/rules/indentRule_test.go
ref. [Incorrect "invalid indentation style" error · Issue #99 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/99)
> fix: indent enum followed by ;

- internal/cmd/subcmds/lint/reporterFlag.go
- internal/linter/report/reporters/jsonReporter.go
- internal/linter/report/reporters/jsonReporter_test.go
Add a json formatter to allow for machine-readable output, as discussed in #101.
> Feat: Add a JSON formatter

- README.md
- _example/config/.protolint.yaml
- _example/proto/simple.proto
- go.mod
- go.sum
- internal/addon/rules/proto3FieldsAvoidRequiredRule.go
- internal/addon/rules/proto3GroupsAvoidRule.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/repeatedFieldNamesPluralizedOption.go
- internal/linter/config/rulesOption.go
- linter/strs/pluralize.go
- linter/strs/pluralize_test.go
ref. https://developers.google.com/protocol-buffers/docs/style#repeated-fields
> feat: Add REPEATED_FIELD_NAMES_PLURALIZED

- _example/proto/issue_128/grpc-gateway_a_bit_of_everything.proto
- go.mod
- go.sum
ref. [swagger annotations break the protolinter · Issue #128 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/128)
> fix: Support parsing grpc-gateway_a_bit_of_everything.proto

- README.md
- internal/addon/rules/enumFieldNamesPrefixRule.go
- internal/addon/rules/enumFieldNamesPrefixRule_test.go
- internal/cmd/subcmds/rules.go
- linter/strs/strs.go
- linter/strs/strs_test.go
ref. [Feature: enum prefix · Issue #152 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/152)
> feat: Add the new rule: ENUM_FIELD_NAMES_PREFIX

- README.md
- _testdata/validconfig/default/.protolint.yml
- _testdata/validconfig/default/child/.protolint.yaml
- internal/linter/config/externalConfigProvider.go
- internal/linter/config/externalConfigProvider_test.go
ref. [Attempt to find configuration file in current and parent folders · Issue #164 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/164)
> Automatically look for a config file in parent repositories all the way up to the root directory

- .goreleaser.yml
ref. https://github.com/yoheimuta/homebrew-protolint/pull/4
> tests: Fix brew style yoheimuta/protolint Error

- Dockerfile
ref. [Problems Running in CI / Docker for Latest? · Issue #174 · yoheimuta/protolint](https://github.com/yoheimuta/protolint/issues/174)
> fix: Put an executable file in PATH

- README.md
- _example/config/.protolint.yaml
- _example/proto/simple.proto
- _testdata/rules/quoteConsistent/double-quoted.proto
- _testdata/rules/quoteConsistent/inconsistent.proto
- _testdata/rules/quoteConsistent/single-quoted.proto
- go.mod
- go.sum
- internal/addon/rules/quoteConsistentRule.go
- internal/addon/rules/quoteConsistentRule_test.go
- internal/cmd/subcmds/rules.go
- internal/linter/config/quoteConsistentOption.go
- internal/linter/config/quoteConsistentOption_test.go
- internal/linter/config/rulesOption.go
- internal/osutil/file.go
- internal/osutil/file_test.go
- linter/fixer/fixer.go
- linter/visitor/baseFixableVisitor.go
ref. `Prefer the use of double quotes for strings.`
- https://developers.google.com/protocol-buffers/docs/style
- https://web.archive.org/web/diff/20190929162216/20210908114957/https://developers.google.com/protocol-buffers/docs/style
> feat: Add QUOTE_CONSISTENT

- Dockerfile
ref. https://github.com/yoheimuta/protolint/issues/177
> chore: Revert the base image to alpine

- README.md
- go.mod
follow-up: https://github.com/yoheimuta/protolint/pull/188
> Change badge

- Dockerfile
upgrade apk packages to get security updates
Fixes #196
> fix: upgrade apk packages

- README.md
- _testdata/rules/enumNamesUpperCamelCase/invalid.proto
- _testdata/rules/enumNamesUpperCamelCase/upperCamelCase.proto
- go.mod
- go.sum
- internal/addon/rules/enumNamesUpperCamelCaseRule.go
- internal/addon/rules/enumNamesUpperCamelCaseRule_test.go
- internal/addon/rules/quoteConsistentRule_test.go
- internal/cmd/subcmds/rules.go
- linter/fixer/fixer.go
- linter/strs/strs.go
- linter/strs/strs_test.go
> feat: Support a fixer for EnumNamesUpperCamelCase

- _example/proto/issue_111/multiple_fixers_applicable.proto
- internal/cmd/subcmds/lint/cmdLint.go
- internal/linter/linter.go
> feat: Parse a file every time a single linter rule runs

- README.md
- _testdata/rules/rpcNamesUpperCamelCase/invalid.proto
- _testdata/rules/rpcNamesUpperCamelCase/upperCamelCase.proto
- internal/addon/rules/quoteConsistentRule_test.go
- internal/addon/rules/rpcNamesUpperCamelCaseRule.go
- internal/addon/rules/rpcNamesUpperCamelCaseRule_test.go
- internal/addon/rules/util_test.go
- internal/cmd/subcmds/rules.go
> Fixer rpc names upper camel case rule

- README.md
- _testdata/rules/enumFieldNamesUpperSnakeCase/invalid.proto
- _testdata/rules/enumFieldNamesUpperSnakeCase/upperSnakeCase.proto
- _testdata/rules/packageNameLowerCase/invalid.proto
- _testdata/rules/packageNameLowerCase/lowerCase.proto
- internal/addon/rules/enumFieldNamesUpperSnakeCaseRule.go
- internal/addon/rules/enumFieldNamesUpperSnakeCaseRule_test.go
- internal/addon/rules/packageNameLowerCaseRule.go
- internal/addon/rules/packageNameLowerCaseRule_test.go
- internal/cmd/subcmds/rules.go
- linter/strs/strs.go
> Add official case fixers

- README.md
- _testdata/rules/enumFieldNamesPrefix/invalid.proto
- _testdata/rules/enumFieldNamesPrefix/prefix.proto
- _testdata/rules/enumFieldNamesZeroValueEndWith/invalid.proto
- _testdata/rules/enumFieldNamesZeroValueEndWith/suffix.proto
- internal/addon/rules/enumFieldNamesPrefixRule.go
- internal/addon/rules/enumFieldNamesPrefixRule_test.go
- internal/addon/rules/enumFieldNamesZeroValueEndWithRule.go
- internal/addon/rules/enumFieldNamesZeroValueEndWithRule_test.go
- internal/cmd/subcmds/rules.go
- linter/strs/strs.go
- linter/strs/strs_test.go
> Add enum fixers

- README.md
- _testdata/rules/proto3FieldsAvoidRequired/avoid_required.proto
- _testdata/rules/proto3FieldsAvoidRequired/invalid.proto
- _testdata/rules/repeatedFieldNamesPluralized/invalid.proto
- _testdata/rules/repeatedFieldNamesPluralized/pluralized.proto
- internal/addon/rules/proto3FieldsAvoidRequiredRule.go
- internal/addon/rules/proto3FieldsAvoidRequiredRule_test.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule_test.go
- internal/cmd/subcmds/rules.go
> Add field fixers

- README.md
- _testdata/rules/order/invalid.proto
- _testdata/rules/order/invalidContiguousMisc.proto
- _testdata/rules/order/invalidMany.proto
- _testdata/rules/order/invalidWithComments.proto
- _testdata/rules/order/order.proto
- _testdata/rules/order/orderContiguousMisc.proto
- _testdata/rules/order/orderMany.proto
- _testdata/rules/order/orderWithComments.proto
- go.mod
- go.sum
- internal/addon/rules/orderRule.go
- internal/addon/rules/orderRule_test.go
- internal/cmd/subcmds/rules.go
- linter/fixer/fixer.go
> Order fixer

- go.mod
- go.sum
re https://github.com/yoheimuta/go-protoparser/issues/68
> Upgrade go-protoparser to v4.5.4

- _proto/plugin.proto
- internal/cmd/cmd.go
- internal/cmd/subcmds/list/cmdList.go
- internal/cmd/subcmds/list/flags.go
the list sub command should output any enabled plugins
> list should output plugins

- .github/workflows/go.yml
- cmd/protoc-gen-protolint/README.md
- internal/cmd/protocgenprotolint/cmd.go
ref. https://github.com/yoheimuta/protolint/issues/264
> feat: Add a parameter of proto_root to protoc-gen-protolint

- README.md
- _testdata/rules/enumFieldNamesPrefix/disable_next.proto
- _testdata/rules/enumFieldNamesPrefix/disable_this.proto
- _testdata/rules/enumFieldNamesZeroValueEndWith/disable_next.proto
- _testdata/rules/enumFieldNamesZeroValueEndWith/disable_this.proto
- internal/addon/rules/enumFieldNamesPrefixRule.go
- internal/addon/rules/enumFieldNamesPrefixRule_test.go
- internal/addon/rules/enumFieldNamesZeroValueEndWithRule.go
- internal/addon/rules/enumFieldNamesZeroValueEndWithRule_test.go
- internal/cmd/subcmds/rules.go
ref. https://github.com/yoheimuta/protolint/issues/269
> Auto disable enum field name rules

- README.md
- _testdata/rules/enumNamesUpperCamelCase/disable_next.proto
- _testdata/rules/enumNamesUpperCamelCase/disable_this.proto
- _testdata/rules/enumNamesUpperCamelCase/invalid.proto
- _testdata/rules/fieldNamesLowerSnakeCase/disable_next.proto
- _testdata/rules/fieldNamesLowerSnakeCase/disable_this.proto
- _testdata/rules/messageNamesUpperCamelCase/disable_next.proto
- _testdata/rules/messageNamesUpperCamelCase/disable_this.proto
- internal/addon/rules/enumNamesUpperCamelCaseRule.go
- internal/addon/rules/enumNamesUpperCamelCaseRule_test.go
- internal/addon/rules/fieldNamesLowerSnakeCaseRule.go
- internal/addon/rules/fieldNamesLowerSnakeCaseRule_test.go
- internal/addon/rules/messageNamesUpperCamelCaseRule.go
- internal/addon/rules/messageNamesUpperCamelCaseRule_test.go
- internal/cmd/subcmds/rules.go
- linter/visitor/extendedAutoDisableVisitor.go
ref. https://github.com/yoheimuta/protolint/issues/269
> Support auto disable enum field message

- README.md
- _testdata/rules/proto3GroupsAvoid/disable_next.proto
- _testdata/rules/proto3GroupsAvoid/disable_this.proto
- _testdata/rules/proto3GroupsAvoid/invalid.proto
- _testdata/rules/proto3GroupsAvoid/valid.proto
- _testdata/rules/repeatedFieldNamesPluralized/disable_next.proto
- _testdata/rules/repeatedFieldNamesPluralized/disable_this.proto
- _testdata/rules/rpcNamesUpperCamelCase/disable_next.proto
- _testdata/rules/rpcNamesUpperCamelCase/disable_this.proto
- _testdata/rules/serviceNamesUpperCamelCase/disable_next.proto
- _testdata/rules/serviceNamesUpperCamelCase/disable_this.proto
- _testdata/rules/serviceNamesUpperCamelCase/invalid.proto
- internal/addon/rules/proto3GroupsAvoidRule.go
- internal/addon/rules/proto3GroupsAvoidRule_test.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule_test.go
- internal/addon/rules/rpcNamesUpperCamelCaseRule.go
- internal/addon/rules/rpcNamesUpperCamelCaseRule_test.go
- internal/addon/rules/serviceNamesUpperCamelCaseRule.go
- internal/addon/rules/serviceNamesUpperCamelCaseRule_test.go
- internal/cmd/subcmds/rules.go
- linter/visitor/extendedAutoDisableVisitor.go
ref. https://github.com/yoheimuta/protolint/issues/269
> Auto disable rpc/service/pluralized/avoid_group

- internal/addon/rules/repeatedFieldNamesPluralizedRule.go
- internal/addon/rules/repeatedFieldNamesPluralizedRule_test.go
ref. https://github.com/yoheimuta/protolint/issues/294
> fix: Make the pluralized rule check in the case-insensitive way

- lib/lint.go
issue: https://github.com/yoheimuta/protolint/issues/322
> feat: API for running protolint from Go code

- README.md
- _testdata/lib/.protolint.yaml
- _testdata/lib/invalid.proto
- _testdata/lib/valid.proto
- lib/lint_test.go
ref.
- https://github.com/yoheimuta/protolint/issues/322
- https://github.com/yoheimuta/protolint/pull/323
> test: Add test code and usage doc for lib/lint.go

- internal/addon/rules/repeatedFieldNamesPluralizedRule_test.go
- linter/strs/pluralize.go
- linter/strs/pluralize_test.go
ref. https://github.com/yoheimuta/protolint/issues/312
> fix: Pluralize 'uri' properly

- internal/addon/rules/fileNamesLowerSnakeCaseRule.go
- internal/addon/rules/fileNamesLowerSnakeCaseRule_test.go
fixed:https://github.com/yoheimuta/protolint/issues/340
> fix: Make dot.separated.proto correct to dot_separated.proto

- internal/addon/rules/enumFieldNamesPrefixRule_test.go
- linter/strs/strs.go
- linter/strs/strs_test.go
ref. https://github.com/yoheimuta/protolint/issues/351
> fix: Handle ListAccountPipedriveOAuthsEnabledFilter as the same way as the previous version

- .github/workflows/publish_npm.yml
Add the NPM_EMAIL Token in order to solve failing upload.
Should solve #356 in addition to #357
> ci: Add NPM_EMAIL

- _testdata/rules/fileNamesLowerSnakeCase/kebab-case.proto
- internal/addon/rules/fileNamesLowerSnakeCaseRule.go
- internal/addon/rules/fileNamesLowerSnakeCaseRule_test.go
- linter/strs/strs.go
- linter/strs/strs_test.go
fix: https://github.com/yoheimuta/protolint/issues/365
> feat: Convert kebab case to snake case

- .github/workflows/publish_wheel.yml
Fixed boolean condition to run twine upload after release
> ci: Corrected deployment

- bdist/py/setup.py
Version must be added after name
> fix: Wheel MetaData is ordered

- internal/cmd/protocgenprotolint/cmd.go
Fix for https://github.com/yoheimuta/protolint/issues/406
> Fixed config_path

- internal/linter/report/reporters/jsonReporter.go
- internal/linter/report/reporters/jsonReporter_test.go
Fix for https://github.com/yoheimuta/protolint/issues/414
> Add severity and basedir to JSON report

- _example/proto/issue_218/bom.proto
- go.mod
- go.sum
fix: https://github.com/yoheimuta/protolint/issues/218
ref: https://github.com/yoheimuta/go-protoparser/pull/89
> Support UTF-8-BOM files

- .github/workflows/go.yml
- .github/workflows/goreleaser.yml
- .github/workflows/publish_wheel.yml
- _example/proto/editions.proto
- _testdata/rules/order/invalidEditions.proto
- _testdata/rules/order/orderEditions.proto
- go.mod
- go.sum
- internal/addon/rules/fileHasCommentRule.go
- internal/addon/rules/indentRule.go
- internal/addon/rules/orderRule.go
- internal/addon/rules/orderRule_test.go
- internal/addon/rules/quoteConsistentRule.go
- linter/visitor/baseVisitor.go
- linter/visitor/extendedAutoDisableVisitor.go
- linter/visitor/extendedDisableRuleVisitor.go
ref. https://github.com/yoheimuta/go-protoparser/releases/tag/v4.12.0
> Protobuf Editions Support

- _example/proto/issue_447/info.proto
- go.mod
- go.sum
- linter/strs/pluralize.go
- linter/strs/pluralize_test.go
- linter/visitor/baseVisitor.go
- linter/visitor/extendedAutoDisableVisitor.go
- linter/visitor/extendedDisableRuleVisitor.go
ref. 
- https://github.com/yoheimuta/protolint/issues/447
- https://github.com/yoheimuta/go-protoparser/issues/93
> Support extension declarations and account info for uncountable names

- .devcontainer/devcontainer.json
Introduce a development container configuration to streamline the protolint development setup. This includes a predefined environment with Go and relevant VSCode settings.
> Add devcontainer configuration for protolint development environment

- go.mod
- go.sum
See https://github.com/yoheimuta/go-protoparser/issues/84
> Update go-protoparser to v4.14.2

- .github/workflows/goreleaser.yml
- build.gradle
ref. https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/
> fix: Migrated from OSSRH to the Central Publisher Portal

- .github/workflows/goreleaser.yml
- README.md
- internal/addon/rules/fieldNumbersOrderAscendingRule.go
- internal/addon/rules/fieldNumbersOrderAscendingRule_test.go
fix: https://github.com/yoheimuta/protolint/issues/495
> fix: Honor option allow_alias=true
